### PR TITLE
Windows pipeline

### PR DESCRIPTION
**Pull request by osolomin90**
Since looks like both of us works on project on non Windows PC I decided to add windows env to pipeline. Also as I know mac osx instances in github actions use free plan minutes 10 times faster so I think we can work on project without osx pipeline at least now.

### CODE REVIEW

**Comment by hdorgeval** [comment]
> Since looks like both of us works on project on non Windows PC 

ha ha, in fact I dev 8 hours a day on Windows machine, and we are doing thousands of run each day of the playwright-fluent package on a windows CI.

**Comment by osolomin90** [comment]
> > Since looks like both of us works on project on non Windows PC
> 
> ha ha, in fact, at work, I dev 8 hours a day on Windows machine, and we are doing thousands of run each day of the playwright-fluent package on a windows CI.

So we do not need this in Actions? Or still it will useful?

**Comment by hdorgeval** [comment]
> So we do not need this in Actions? Or will it still useful?

You contribution is very useful. I propose to experiment it and to adjust afterwards if necessary.

**Comment by hdorgeval** [comment]
Hi @osolomin90, it seems to work great on the Github actions: both Linux and Windows env runs at the same time.

**Pull request merged**
